Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YummyProject.Context;
using YummyProject.Models;

namespace YummyProject.Controllers
{
    public class AboutController : Controller
    {
        YummyContext context=new YummyContext();
        public ActionResult Index()
        {
            var values = context.Abouts.ToList();
            return View(values);
        }


        public ActionResult AddAbout()
        {
            return View();
        }

        [HttpPost]

        public ActionResult AddAbout(About about)
        {
            if (about.ImageFile != null)
            {
                var currentDirectory = AppDomain.CurrentDomain.BaseDirectory;
                var saveLocation = currentDirectory + "images\\";
                var fileName = Path.Combine(saveLocation, about.ImageFile.FileName);
                about.ImageFile.SaveAs(fileName);
                about.ImageUrl = "/images/" + about.ImageFile.FileName;
            }

            if (about.ImageFile2 != null)
            {
                var currentDirectory = AppDomain.CurrentDomain.BaseDirectory;
                var saveLocation = currentDirectory + "images\\";
                var fileName2 = Path.Combine(saveLocation, about.ImageFile2.FileName);
                about.ImageFile2.SaveAs(fileName2);
                about.ImageUrl2 = "/images/" + about.ImageFile2.FileName;
            }


            context.Abouts.Add(about);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeleteAbout(int id)
        {
            var value = context.Abouts.Find(id);
            context.Abouts.Remove(value);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UpdateAbout(int id)
        {
            var about = context.Abouts.Find(id);
            return View(about);
        }

        [HttpPost]
        public ActionResult UpdateAbout(About about)
        {
            var value = context.Abouts.Find(about.AboutId);

            if (value != null)
            {
                value.Item1 = about.Item1;
                value.Item2 = about.Item2;
                value.Item3 = about.Item3;
                value.Description = about.Description;
                value.VideoUrl = about.VideoUrl;

                if (about.ImageFile != null)
                {
                    if (!string.IsNullOrEmpty(value.ImageUrl))
                    {
                        var currentDirectory = AppDomain.CurrentDomain.BaseDirectory;
                        var oldFilePath = currentDirectory + value.ImageUrl.Replace("/", "\\");
                        if (System.IO.File.Exists(oldFilePath))
                        {
                            System.IO.File.Delete(oldFilePath);
                        }
                    }
                    var saveLocation = AppDomain.CurrentDomain.BaseDirectory + "images\\";
                    var fileName = Path.Combine(saveLocation, about.ImageFile.FileName);
                    about.ImageFile.SaveAs(fileName);
                    value.ImageUrl = "/images/" + about.ImageFile.FileName;

                 
                }
                if (about.ImageFile2 != null)
                {
                    if (!string.IsNullOrEmpty(value.ImageUrl2))
                    {
                        var currentDirectory = AppDomain.CurrentDomain.BaseDirectory;
                        var oldFilePath = currentDirectory + value.ImageUrl.Replace("/", "\\");
                        if (System.IO.File.Exists(oldFilePath))
                        {
                            System.IO.File.Delete(oldFilePath);
                        }
                    }
                    var saveLocation = AppDomain.CurrentDomain.BaseDirectory + "images\\";
                    var fileName2 = Path.Combine(saveLocation, about.ImageFile2.FileName);
                    about.ImageFile2.SaveAs(fileName2);
                    value.ImageUrl2 = "/images/" + about.ImageFile2.FileName;
                }

                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

      
    }
}

Controllers/AdminLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YummyProject.Context;

namespace YummyProject.Controllers
{
    [Authorize]
    public class AdminLayoutController : Controller
    {
        YummyContext context = new YummyContext();
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult AdminLayoutHead()
        {
            return PartialView();
        }
        public PartialViewResult AdminLayoutSideBar()
        {

            return PartialView();
        }

        public PartialViewResult AdminLayoutNavBar()
        {
            return PartialView();
        }

        public PartialViewResult AdminLayoutScripts()
        {
            return PartialView();
        }


    }
}

Controllers/ChefController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YummyProject.Context;
using YummyProject.Models;
using System.Data.Entity;


namespace YummyProject.Controllers
{
    public class ChefController : Controller
    {
        YummyContext context = new YummyContext();
        public ActionResult Index()
        {
            var values = context.Chefs
                .Include("ChefSocials")
                .ToList();

            return View(values);
        }


        public ActionResult AddChef()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddChef(Chef chef, List<string> SocialMediaName, List<string> SocialMediaUrl, List<string> SocialMediaIcon)
        {
            if (ModelState.IsValid)
            {

                if (chef.ImageFile != null)
                {
                    var currentDirectory = AppDomain.CurrentDomain.BaseDirectory;
                    var saveLocation = currentDirectory + "images\\";
                    var fileName = Path.Combine(saveLocation, chef.ImageFile.FileName);
                    chef.ImageFile.SaveAs(fileName);
                    chef.ImageUrl = "/images/" + chef.ImageFile.FileName;
                }


                context.Chefs.Add(chef);
                context.SaveChanges();


                for (int i = 0; i < SocialMediaName.Count; i++)
                {
                    var chefSocial = new ChefSocial
                    {
                        SocialMediaName = SocialMediaName[i],
                        Url = SocialMediaUrl[i],
                        Icon = SocialMediaIcon != null && SocialMediaIcon.Count > i ? SocialMediaIcon[i] : null,
                        ChefId = chef.ChefId
                    };

                    context.ChefSocials.Add(chefSocial);
                }

                context.SaveChanges();


                return RedirectToAction("Index");
            }


            return View(chef);
        }
        public ActionResult UpdateChef(int id)
        {
            var chef = context.Chefs
                              .Include(c => c.ChefSocials)
                              .FirstOrDefault(c => c.ChefId == id);

            if (chef == null)
            {
                return HttpNotFound();
            }

            return View(chef);
        }

        [HttpPost]
        public ActionResult UpdateChef(Chef chef, List<string> SocialMediaName, List<string> SocialMediaUrl, List<string> SocialMediaIcon)
        {
            // Şefi buluyoruz
            var value = context.Chefs
                               .Include(c => c.ChefSocials)
                               .FirstOrDefault(c => c.ChefId == chef.ChefId);

            if (value != null)
            {
                // Chef bilgilerini güncelleme
                value.Name = chef.Name;
                value.Title = chef.Title;
                value.Description = chef.Description;

                // Yeni resim varsa güncelleme
                if (chef.ImageFile != null)
                {
                    if (!string.IsNullOrEmpty(value.ImageUrl))
                    {
                        var currentDirectory = AppDomain.CurrentDomain.BaseDirectory;
                        var oldFilePath = currentDirectory + value.ImageUrl.Replace("/", "\\");
                        if (System.IO.File.Exists(oldFilePath))
                        {
                            System.IO.File.Delete(oldFilePath);
                        }
                    }

                    var saveLocation = AppDomain.CurrentDomain.BaseDirectory + "images\\";
                    var fileName = Path.Combine(saveLocation, chef.ImageFile.FileName);
                    chef.ImageFile.SaveAs(fileName);
                    value.ImageUrl = "/images/" + chef.ImageFile.FileName;
                }

                // Mevcut sosyal medya bilgilerini güncelleme
                for (int i = 0; i < SocialMediaName.Count; i++)
                {
                    var socialMedia = value.ChefSocials.ElementAtOrDefault(i);
                    if (socialMedia != null)
                    {
                        // Mevcut öğe varsa, bilgilerini güncelle
                        socialMedia.SocialMediaName = SocialMediaName[i];
                        socialMedia.Url = SocialMediaUrl[i];
                        socialMedia.Icon = SocialMediaIcon != null && SocialMediaIcon.Count > i ? SocialMediaIcon[i] : null;
                    }
                    else
                    {
                        // Yeni öğe ekle
                        value.ChefSocials.Add(new ChefSocial
                        {
                            SocialMediaName = SocialMediaName[i],
                            Url = SocialMediaUrl[i],
                            Icon = SocialMediaIcon != null && SocialMediaIcon.Count > i ? SocialMediaIcon[i] : null,
                            ChefId = value.ChefId
                        });
                    }
                }

                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }


        public ActionResult DeleteSocialMedia()
        {
            // Şeflerin sosyal medya hesaplarını ve şefin adını alıyoruz
            var values = context.ChefSocials.Include(c => c.Chef).ToList();
            return View(values);  // Şefin adı ve sosyal medya bilgilerini view'a gönderiyoruz
        }

        [HttpPost]
        public ActionResult DeleteSocialMedia(int id)
        {
            // Silinecek sosyal medya kaydını buluyoruz
            var value = context.ChefSocials.Find(id);
            if (value != null)
            {
                // Silinen sosyal medya ile ilişkilendirilmiş şef bilgisi de dahil
                context.ChefSocials.Remove(value);
                context.SaveChanges();
            }

            return RedirectToAction("DeleteSocialMedia");
        }


        public ActionResult AddSocialMedia()
        {
            // Şefleri ViewBag üzerinden view'e gönderiyoruz
            var chefs = context.Chefs.ToList();
            ViewBag.Chefs = new SelectList(chefs, "ChefId", "Name");

            return View();
        }

        [HttpPost]
        public ActionResult AddSocialMedia(int chefId, string socialMediaName, string socialMediaUrl, string socialMediaIcon)
        {
            // Şef bulunuyor
            var chef = context.Chefs.FirstOrDefault(c => c.ChefId == chefId);

            if (chef != null)
            {
                // Yeni bir sosyal medya ekleniyor
                var newSocialMedia = new ChefSocial
                {
                    SocialMediaName = socialMediaName,
                    Url = socialMediaUrl,
                    Icon = socialMediaIcon,
                    ChefId = chefId
                };

                context.ChefSocials.Add(newSocialMedia);
                context.SaveChanges();

                TempData["SuccessMessage"] = "Social Media added successfully!";
                return RedirectToAction("AddSocialMedia");
            }

            TempData["ErrorMessage"] = "Error while adding Social Media!";
            return View();
        }



        public ActionResult DeleteChef(int id)
        {
            var value = context.Chefs.Find(id);
            context.Chefs.Remove(value);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

     
    }

}

Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YummyProject.Context;
using YummyProject.Models;

namespace YummyProject.Controllers
{
    public class EventController : Controller
    {
        YummyContext context=new YummyContext();
        public ActionResult Index()
        {
            var valeus=context.Events.ToList();
            return View(valeus);
        }

        public ActionResult AddEvent()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddEvent(Event evnt)
        {
            if (evnt.ImageFile != null)
            {
                var currentDirectory = AppDomain.CurrentDomain.BaseDirectory;
                var saveLocation = currentDirectory + "images\\";
                var fileName = Path.Combine(saveLocation, evnt.ImageFile.FileName);
                evnt.ImageFile.SaveAs(fileName);
                evnt.ImageUrl = "/images/" + evnt.ImageFile.FileName;
            }

            context.Events.Add(evnt);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UpdateEvent(int id)
        {
            var evnt = context.Events.Find(id);
            return View(evnt);
        }

        [HttpPost]
        public ActionResult UpdateEvent(Event evnt)
        {
            var value = context.Events.Find(evnt.EventId);

            if (value != null)
            {
                value.Title = evnt.Title;
                value.Description = evnt.Description;
                value.Price = evnt.Price;

                if (evnt.ImageFile != null)
                {
                    if (!string.IsNullOrEmpty(value.ImageUrl))
                    {
                        var currentDirectory = AppDomain.CurrentDomain.BaseDirectory;
                        var oldFilePath = currentDirectory + value.ImageUrl.Replace("/", "\\");
                        if (System.IO.File.Exists(oldFilePath))
                        {
                            System.IO.File.Delete(oldFilePath);
                        }
                    }
                    var saveLocation = AppDomain.CurrentDomain.BaseDirectory + "images\\";
                    var fileName = Path.Combine(saveLocation, evnt.ImageFile.FileName);
                    evnt.ImageFile.SaveAs(fileName);
                    value.ImageUrl = "/images/" + evnt.ImageFile.FileName;
                }

                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public ActionResult DeleteEvent(int id)
        {
            var value = context.Events.Find(id);
            context.Events.Remove(value);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/AdminLayout/AdminLayoutHead.cshtml
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="~/Templates/sb-admin/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

    <style>
        .partial-container {
            border: 1px solid #ddd; /* Kenarlık stili */
            border-radius: 5px; /* Köşelerin yuvarlanması */
            padding: 15px; /* İç boşluk */
            margin-bottom: 20px; /* Alt boşluk */
            margin-top: 20px; /* Üst boşluk */
            background-color: #f9f9f9; /* Hafif bir arka plan rengi */
        }
    </style>

</head>

Views/AdminLayout/AdminLayoutNavBar.cshtml
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="index.html">Admin Panel</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
            <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/Profile/Index">Profile</a></li>

                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="/Login/SignOut">Logout</a></li>
            </ul>
        </li>
    </ul>
</nav>

Views/AdminLayout/AdminLayoutScripts.cshtml
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="~/Templates/sb-admin/js/scripts.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="~/Templates/sb-admin/assets/demo/chart-area-demo.js"></script>
<script src="~/Templates/sb-admin/assets/demo/chart-bar-demo.js"></script>
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
<script src="~/Templates/sb-admin/js/datatables-simple-demo.js"></script>

Views/AdminLayout/AdminLayoutSideBar.cshtml
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Dashboard</div>
                <a class="nav-link" href="@Url.Action("Index", "Dashboard")">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Dashboard
                </a>
                <div class="sb-sidenav-menu-heading">Admin Operations</div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Admin Operations
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="@Url.Action("Index", "Feature")">Feature</a>
                        <a class="nav-link" href="@Url.Action("Index", "About")">About Us</a>
                        <a class="nav-link" href="@Url.Action("Index", "Service")">Services</a>
                        <a class="nav-link" href="@Url.Action("Index", "Product")">Products</a>
                        <a class="nav-link" href="@Url.Action("Index", "Testimonial")">Testimonial</a>
                        <a class="nav-link" href="@Url.Action("Index", "Event")">Events</a>
                        <a class="nav-link" href="@Url.Action("Index", "Chef")">Chefs</a>
                        <a class="nav-link" href="@Url.Action("Index", "Booking")">Booking</a>
                        <a class="nav-link" href="@Url.Action("Index", "Gallery")">Gallery</a>
                        <a class="nav-link" href="@Url.Action("Index", "Contact")">Contact</a>
                        <a class="nav-link" href="@Url.Action("Index", "Message")">Messages</a>
                    </nav>
                </div>
                
                <div class="sb-sidenav-menu-heading">Addons</div>
                <a class="nav-link" href="@Url.Action("Index", "Default")" target="_blank">
                    <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                   Go to site
                </a>
                
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Logged in as:</div>
            Admin Panel
        </div>
    </nav>
</div>

Views/AdminLayout/Index.cshtml
@{
    Layout = null;
}



<!DOCTYPE html>
<html lang="en">

@Html.Action("AdminLayoutHead", "AdminLayout")

<body class="sb-nav-fixed">
    @Html.Action("AdminLayoutNavbar", "AdminLayout")
    <div id="layoutSidenav">
        @Html.Action("AdminLayoutSidebar", "AdminLayout")
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <div class="partial-container">
                        @RenderBody()
                    </div>
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    @Html.Action("AdminLayoutScripts", "AdminLayout")

</body>
</html>